# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kvs_pb2 as kvs__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kvs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KVSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insere = channel.unary_unary(
                '/kvs.KVS/Insere',
                request_serializer=kvs__pb2.ChaveValor.SerializeToString,
                response_deserializer=kvs__pb2.Versao.FromString,
                _registered_method=True)
        self.Consulta = channel.unary_unary(
                '/kvs.KVS/Consulta',
                request_serializer=kvs__pb2.ChaveVersao.SerializeToString,
                response_deserializer=kvs__pb2.Tupla.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/kvs.KVS/Remove',
                request_serializer=kvs__pb2.ChaveVersao.SerializeToString,
                response_deserializer=kvs__pb2.Versao.FromString,
                _registered_method=True)
        self.InsereVarias = channel.stream_stream(
                '/kvs.KVS/InsereVarias',
                request_serializer=kvs__pb2.ChaveValor.SerializeToString,
                response_deserializer=kvs__pb2.Versao.FromString,
                _registered_method=True)
        self.ConsultaVarias = channel.stream_stream(
                '/kvs.KVS/ConsultaVarias',
                request_serializer=kvs__pb2.ChaveVersao.SerializeToString,
                response_deserializer=kvs__pb2.Tupla.FromString,
                _registered_method=True)
        self.RemoveVarias = channel.stream_stream(
                '/kvs.KVS/RemoveVarias',
                request_serializer=kvs__pb2.ChaveVersao.SerializeToString,
                response_deserializer=kvs__pb2.Versao.FromString,
                _registered_method=True)
        self.Snapshot = channel.unary_stream(
                '/kvs.KVS/Snapshot',
                request_serializer=kvs__pb2.Versao.SerializeToString,
                response_deserializer=kvs__pb2.Tupla.FromString,
                _registered_method=True)


class KVSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Insere(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consulta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsereVarias(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultaVarias(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveVarias(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Snapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insere': grpc.unary_unary_rpc_method_handler(
                    servicer.Insere,
                    request_deserializer=kvs__pb2.ChaveValor.FromString,
                    response_serializer=kvs__pb2.Versao.SerializeToString,
            ),
            'Consulta': grpc.unary_unary_rpc_method_handler(
                    servicer.Consulta,
                    request_deserializer=kvs__pb2.ChaveVersao.FromString,
                    response_serializer=kvs__pb2.Tupla.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=kvs__pb2.ChaveVersao.FromString,
                    response_serializer=kvs__pb2.Versao.SerializeToString,
            ),
            'InsereVarias': grpc.stream_stream_rpc_method_handler(
                    servicer.InsereVarias,
                    request_deserializer=kvs__pb2.ChaveValor.FromString,
                    response_serializer=kvs__pb2.Versao.SerializeToString,
            ),
            'ConsultaVarias': grpc.stream_stream_rpc_method_handler(
                    servicer.ConsultaVarias,
                    request_deserializer=kvs__pb2.ChaveVersao.FromString,
                    response_serializer=kvs__pb2.Tupla.SerializeToString,
            ),
            'RemoveVarias': grpc.stream_stream_rpc_method_handler(
                    servicer.RemoveVarias,
                    request_deserializer=kvs__pb2.ChaveVersao.FromString,
                    response_serializer=kvs__pb2.Versao.SerializeToString,
            ),
            'Snapshot': grpc.unary_stream_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=kvs__pb2.Versao.FromString,
                    response_serializer=kvs__pb2.Tupla.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvs.KVS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvs.KVS', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KVS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Insere(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvs.KVS/Insere',
            kvs__pb2.ChaveValor.SerializeToString,
            kvs__pb2.Versao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consulta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvs.KVS/Consulta',
            kvs__pb2.ChaveVersao.SerializeToString,
            kvs__pb2.Tupla.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvs.KVS/Remove',
            kvs__pb2.ChaveVersao.SerializeToString,
            kvs__pb2.Versao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsereVarias(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kvs.KVS/InsereVarias',
            kvs__pb2.ChaveValor.SerializeToString,
            kvs__pb2.Versao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultaVarias(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kvs.KVS/ConsultaVarias',
            kvs__pb2.ChaveVersao.SerializeToString,
            kvs__pb2.Tupla.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveVarias(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kvs.KVS/RemoveVarias',
            kvs__pb2.ChaveVersao.SerializeToString,
            kvs__pb2.Versao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kvs.KVS/Snapshot',
            kvs__pb2.Versao.SerializeToString,
            kvs__pb2.Tupla.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
